<?php

namespace Tests\Browser;

use App\User;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\DuskTestCase;
use Laravel\Dusk\Browser;
use Illuminate\Foundation\Testing\DatabaseMigrations;

class LoginTest extends DuskTestCase
{

    use DatabaseMigrations;
    use DatabaseTransactions;

    protected $LOGIN_FAILED_MESSAGE = 'These credentials do not match our records.';
    /**
     * A Dusk test example.
     *
     * @return void
     */

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = User::first();
    }

    public function test_failed_login(){
        $this->browse(function (Browser $browser) {
            $browser->visit('/login')
                ->assertSee('E-Mail Address')
                ->assertSee('Password')
                ->assertTitle('Login')
                ->assertPathIs('/login')
                ->type('email',$this->user->email)
                ->type('password', 'secre1t')
                ->press('Login')
                ->assertSee($this->LOGIN_FAILED_MESSAGE);

        });
    }


    public function test_successfully_login()
    {
        $this->browse(function (Browser $browser) {
            $browser->visit('/login')
                ->assertSee('E-Mail Address')
                ->assertSee('Password')
                ->assertTitle('Login')
                ->assertPathIs('/login')
                ->type('email',$this->user->email)
                ->type('password', 'secret')
                ->press('Login')
                ->assertPathIs('/home');

        });
    }


    public function test_completed_element_in_login_page(){
        $this->assertTrue(true);
    }



}
