<?php

use Illuminate\Database\Seeder;

class BatikTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('batik')->insert([
            array('nama_batik' => 'Arum Dalu', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Blibar11', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Yogyakarta'),
            array('nama_batik' => 'Blibar12', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Yogyakarta'),
            array('nama_batik' => 'Blibar13', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Yogyakarta'),
            array('nama_batik' => 'Blibar14', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Yogyakarta'),
            array('nama_batik' => 'Blibar21', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Yogyakarta'),
            array('nama_batik' => 'Blibar22', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Yogyakarta'),
            array('nama_batik' => 'Blibar23', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Yogyakarta'),
            array('nama_batik' => 'Blibar24', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Yogyakarta'),
            array('nama_batik' => 'Budi Luhur1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Budi Luhur2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Ceplok Abimanyu1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Yogyakarta'),
            array('nama_batik' => 'Ceplok Abimanyu2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Yogyakarta'),
            array('nama_batik' => 'Ceplok Abimanyu3', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Yogyakarta'),
            array('nama_batik' => 'Ceplok Ambar Sekar', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Yogyakarta'),
            array('nama_batik' => 'Ceplok Gambir Anom', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Yogyakarta'),
            array('nama_batik' => 'Ceplok Gusti Putri1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Yogyakarta'),
            array('nama_batik' => 'Ceplok Jelanggrong', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Yogyakarta'),
            array('nama_batik' => 'Ceplok Keci1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Ceplok Keci2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Ceplok Kembang Tebu1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Ceplok Kembang Tebu2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Ceplok Kembang Waru1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Ceplok Kembang Waru2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Ceplok Kenongo1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Ceplok Kenongo2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Ceplok Kenongo3', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Ceplok Lenggang Kangkung', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Ceplok Mawar Sari', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Ceplok Mulyo1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Ceplok Mulyo2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Ceplok Pamugari 11', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Ceplok Pamugari 12', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Ceplok Pamugari 21', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Ceplok Pamugari 22', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Ceplok Prana Jiwa1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Ceplok Prana Jiwa2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Sekar Bangah1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Sekar Bangah2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Ceplok Sekar Sidoguri', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Ceplok Sirap', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Ceplok Tanjungsari1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Ceplok Tanjungsari2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Ceplok Wahyuningrat1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Ceplok Wahyuningrat2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Gambiro Wati1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Gambiro Wati2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Gendala Giri1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Gendala Giri2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Glagah Kurung', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Grompol I1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Grompol I2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Grompol II1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Grompol II2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kartiko Wati1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kartiko Wati2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kembang Kapas1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kembang Kapas2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kembang Kapas3', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kembang Pala1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kembang Pala2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kembang Tanjung1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kembang Tanjung2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kenanga Sari1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kenanga Sari2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kerton Bekingking', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kerton Pari Anom', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Konang Sakebon1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Konang Sakebon2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kotak Banci Kasut', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kotak Jamblang', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kotak Peksi Kurung1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kotak Peksi Kurung2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kupu Anom', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Lara Sedowo1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Lara Sedowo2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Limaran1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Limaran2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Melati Rinonce I1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Melati Rinonce I2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Sawo Bludru1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Sawo Bludru2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Sekar Kopi1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Sekar Kopi2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Sekar Sembojo', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Sekar Sidoguri1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Sekar Sidoguri2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Sekar Tanjung', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Sekar Turi1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Sekar Turi2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Sido Mulyo II1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Sido Mulyo II2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Sumber Lintang1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Sumber Lintang2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Sumber Lintang3', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Triloka', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Ceplok Kawung Grinsing', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kawung Beton', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kawung Brendhi', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kawung Cacah Gori', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kawung Galar', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kawung Gamblok', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kawung Kepyar', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kawung Ndil', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kawung Picis', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kawung Plentong', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kawung Putri', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kawung Sen', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kawung Ukel', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kawung Uter', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Kawung Manila', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Sawo Pecah', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Sawo Tanjungsari', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Lereng Dana Tirta', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Lereng Abiyoso', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Lereng Bangun Ningrat1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Lereng Bangun Ningrat', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Lereng Blambangan', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Lereng Cagak Talang', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Lereng Candi Puro', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Lereng Golang galing', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Lereng Kembang Bayem', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Lereng Modang', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Lereng Paripurno', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Lereng Prana Jiwo', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Rujak Senthe I', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Lereng Rujak Senthe II-1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Lereng Rujak Senthe II', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Lereng Rujak Tales', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Lereng Tatagati', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Lereng Tritis', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Lereng Udan Riris', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Lereng Uceng Udik', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Lereng Sukoreno', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Lereng Weningsari', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Ceplok Liring', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Dara Gelar', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Grompol', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Kartika', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Kapulogo', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Nagasari', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Nujuprana', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Pandanwangi', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Rumpuk', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Sekar Andala', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Sekar Anggrek', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Sekar Bangah', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Sekar Blimbing', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Sekar Cendul', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Sekar Cengkeh I', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Sekar Cengkeh II', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Sekar Delimo', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Sekar Giwang', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Sekar Jagung', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Sekar Jali', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Sekar Jambe', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Sekar Jambet', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Sekar Kenongo', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Sekar Kentang', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Sekar Kepel', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Sekar Manggar', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Sekar Melati', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Sekar Menur', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Sekar Pala I', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Sekar Pala II', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Sekar Polong', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Sekar Randu I', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Sekar Randu II', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Sekar Randu III', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Sekar Sawo', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Sekar Sedah', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Sekar Tebu', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Sekar Teleng I', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Sekar Teleng II', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Tanjung Gunung I', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Tanjung Gunung II', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Nitik Tanjung Gunung III', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Curiga', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Curiga Nata', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Gendewa', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Harjono', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Joyopuro', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Karno', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Komojoyo', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Kondur Baris', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Kumudaningrat', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Kusumo', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Kusumo Besar', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Laras Madyo', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Larasati', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Muncar 1', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Muncar 2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Muninggar', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Nengkulo', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Ningsih', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Pandan Sari', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Parikesit Putri', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Poncowati', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Rusak Barong', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Samba', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Sawut 2', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Sawut Seling', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Semiaji', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Seno', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Seto', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Sidoreno', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Sisik', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Srimpi', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Sukawati', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Sumbo', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara'),
            array('nama_batik' => 'Parang Tarupulo', 'makna_batik' => '', 'sejarah_batik' => '', 'asal_daerah' => 'Jepara')
        ]);
    }
}
