image: php:5.6


before_script:
  - bash .gitlab-ci.sh

test:
  script:
    - mkdir report
    - vendor/bin/phpunit --colors --coverage-html report/

coverage:
  type: deploy
  dependencies:
    - test
  script:
    - mkdir report
    - vendor/bin/phpunit --colors --coverage-html report/
    - ls -la
  artifacts:
    paths:
      - public/

staging:
  type: deploy
  dependencies:
    - test
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - apt-get install rubygems-integration
  - gem install dpl
  - dpl --provider=heroku --app=batique-staging --api-key=0ed5e2a2-11f9-43d3-98ad-425ee0680012
  only: 
  - gitlab-ci-runner

production:
  type: deploy
  dependencies:
    - test
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - apt-get install rubygems-integration
  - gem install dpl
  - dpl --provider=heroku --app=batique --api-key=0ed5e2a2-11f9-43d3-98ad-425ee0680012
  only: 
  - master