before_script:
  - bash .gitlab-ci.sh

test:
  image: php:5.6
  script:
    - vendor/bin/phpunit --colors --coverage-html ./report

coverage:
  type: deploy
  dependencies:
    - test
  script:
    - mv report/ public/
  artifacts:
    paths:
      - public/

# staging:
#   type: deploy
#   dependencies:
#     - test
#   script:
#   - apt-get update -qy
#   - apt-get install -y ruby-dev
#   - gem install dpl
#   - cd lipsy
#   - dpl --provider=heroku --app=ppldep --api-key=dbcbb340-0714-4db6-9508-15b84165ed4b