<?php

namespace Tests\Feature;

use App\Batik;
use App\TagBatik;
use App\User;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class AuthTest extends TestCase
{

    use DatabaseMigrations;
//    use WithoutMiddleware;


    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test_login_page_open_by_unauthenticated_user()
    {
        $response = $this->get(action('Auth\LoginController@showLoginForm'));
        $response->assertStatus(200);
    }

    public function test_login_page_open_by_authenticated_user()
    {
        $user = factory(User::class)->create();
        $response = $this
            ->actingAs($user)
            ->get(action('Auth\LoginController@showLoginForm'));
        $response->assertStatus(302);
    }

    public function test_login_page_open_by_authenticated_user_as_admin()
    {
        $user = factory(User::class)->make();
        $user->is_admin = true;
        $user->save();
        $response = $this
            ->actingAs($user)
            ->get(action('Auth\LoginController@showLoginForm'));
        $response->assertStatus(302);
    }

    public function test_reset_password_page_by_unauthenticated_user(){
        $response = $this->get(action('Auth\ForgotPasswordController@showLinkRequestForm'));
        $response->assertStatus(200);
    }

    public function test_reset_password_page_by_authenticated_user(){
        $user = factory(User::class)->create();
        $response = $this
            ->actingAs($user)
            ->get(action('Auth\ForgotPasswordController@showLinkRequestForm'));
        $response->assertStatus(302);
    }

    public function test_reset_password_page_by_authenticated_user_as_admin(){
        $user = factory(User::class)->make();
        $user->is_admin = true;
        $user->save();
        $response = $this
            ->actingAs($user)
            ->get(action('Auth\ForgotPasswordController@showLinkRequestForm'));
        $response->assertStatus(302);
    }

    public function test_register_page_by_unathenticated_user(){
        $response = $this->get(action('Auth\RegisterController@showRegistrationForm'));
        $response->assertStatus(200);
    }

    public function test_register_page_by_authenticated_user(){
        $user = factory(User::class)->create();
        $response = $this
            ->actingAs($user)
            ->get(action('Auth\RegisterController@showRegistrationForm'));
        $response->assertStatus(302);
    }

    public function test_register_page_by_authenticated_user_as_admin(){
        $user = factory(User::class)->make();
        $user->is_admin = true;
        $user->save();
        $response = $this
            ->actingAs($user)
            ->get(action('Auth\RegisterController@showRegistrationForm'));
        $response->assertStatus(302);
        $response->assertRedirect(action('PageController@index'));

    }


}
