<?php

namespace Tests\Feature;

use App\User;
use Faker\Factory;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class PostThreadTest extends TestCase
{

    use DatabaseMigrations;
    use WithoutMiddleware;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

    }

    public function test_thread_post_by_unauthenticated_user()
    {
        $response = $this->post(action('ThreadController@store'), [
            'nama_thread' => "sasasasas",
            'content' => "SASasasas"
        ]);
        $response->assertStatus(401);
    }

    public function test_thread_post_by_authenticated_user()
    {
        $faker = Factory::create();
        $user = factory(User::class)->make();
        $user->is_admin = true;
        $user->save();
        $response = $this
            ->actingAs($user)
            ->post(action('ThreadController@store'), [
                'nama_thread' => "asasasas",
                'content' => "asasasasas"
             ]);
        $response->assertStatus(302);
        $response->assertRedirect('/');
    }
}
