<?php

namespace Tests\Unit;

use App\Comment;
use App\Thread;
use App\User;
use Tests\TestCase;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class TulisBalasCommentTest extends TestCase
{

    use DatabaseMigrations;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $user = factory(User::class)->create();
        $thread = factory(Thread::class)->make();
        $user->create_thread()->save($thread);
        $comment = factory(Comment::class)->make();
        $comment->thread_id = $thread->id;
        $user->comments()->save($comment);
        $this->comment = $comment;
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function test_a_comment_has_a_judul_komentar_attribute()
    {
        $this->assertArrayHasKey('judul_komentar', $this->comment->getAttributes());
    }

    public function test_a_comment_has_a_isi_komentar_attribute()
    {
        $this->assertArrayHasKey('isi_komentar', $this->comment->getAttributes());
    }

    public function test_a_comment_has_a_thread_id_attribute()
    {
        $this->assertArrayHasKey('thread_id', $this->comment->getAttributes());
    }

    public function test_a_comment_has_a_comment_by_attribute()
    {
        $this->assertArrayHasKey('comment_by', $this->comment->getAttributes());
    }

    public function test_a_comment_has_a_correct_isi_komentar(){
        $comment = Comment::find($this->comment->id);
        $this->assertEquals($this->comment->isi_komentar, $comment->isi_komentar);
    }

    public function test_a_comment_has_a_correct_judul_komentar(){
        $comment = Comment::find($this->comment->id);
        $this->assertEquals($this->comment->judul_komentar, $comment->judul_komentar);
    }

    public function test_a_comment_has_a_correct_thread_id(){
        $comment = Comment::find($this->comment->id);
        $this->assertEquals($this->comment->thread_id, $comment->thread_id);
    }

    public function test_a_comment_has_a_correct_comment_by(){
        $comment = Comment::find($this->comment->id);
        $this->assertEquals($this->comment->comment_by, $comment->comment_by);
    }
}
